### ISSUE TITLE
Bundle.identifier with constant values?

### ISSUE THREAD

**Issue by michaelonken** [ahdis/matchbox-formfiller#117]
It seems like all Bundles (currently being on the server) do have the same identifiers:

```
"identifier": {
        "system": "urn:ietf:rfc:3986",
        "value": "urn:uuid:26d3dff7-ab05-4737-a49c-5eccd33595f7"
}
```

e.g. http://test.ahdis.ch/matchbox/fhir/Bundle/1212, http://test.ahdis.ch/matchbox/fhir/Bundle/1213, http://test.ahdis.ch/matchbox/fhir/Bundle/1214

**Comment by oliveregger** [comment]
the bundles have now different identifier.

https://test.ahdis.ch/matchbox/fhir/Bundle/3024 urn:uuid:3b22777b-9db9-4703-9777-99dc2d1c7ec5
https://test.ahdis.ch/matchbox/fhir/Bundle/30241 urn:uuid:7d9b3262-03d4-4307-a4c7-4cca236f6f52
