### ISSUE TITLE
Differentiation of incoming and outgoing orders (Bundles)

### ISSUE THREAD

**Issue by ziegm** [ahdis/matchbox-formfiller#85]
* Unterscheidung der Bundles: eingehender Auftrag, ausgehender Auftrag?
* Wie kann die Information auf dem Server abgespeichert werden?

**Comment by ziegm** [comment]
**Vorschlag:**
* Eingehendes Bundle hat im [ServiceRequest](http://fhir.ch/ig/ch-orf/StructureDefinition-ch-orf-servicerequest.html) den gleichen **identifier:placerOrderIdentifier** wie der separat abgespeicherte Identifier auf dem Server.
* placerOrderIdentifier auf dem Server:
```json
{
    "resourceType": "Basic",
    "id": "placer-order-identifier",
    "extension": [
        {
            "url": "http://fhir.ch/ig/ch-orf/StructureDefinition/placer-order-identifier",
            "valueIdentifier": {
                "type": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                            "code": "PLAC"
                        }
                    ]
                },
                "system": "urn:oid:1.3.4.5.6.7",
                "value": "123"
            }
        }
    ],
    "code": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                "code": "PLAC",
                "display": "Placer Identifier"
            }
        ]
    }
}
```

**Comment by oliveregger** [comment]
Dann unterscheiden wir nach allen Aufträgen die aus einer Organisation kommen? Finde ich einen sehr guten Vorschlag. Würde nur anstelle fixer id auch wieder einen identifier definieren, wie bei der Default Questionnaire Response.

```json
  "identifier": [
      {
        "system": "http://ahdis.ch/fhir/Questionnaire",
        "value": "PLACER"
      }
    ],
```

**Comment by ziegm** [comment]
@joelfisch
Was denkst du über den Vorschlag?
https://github.com/ahdis/matchbox-formfiller/blob/issue85/src/examples/placer-order-identifier.json

@timdorner
Könnt ihr im Kontext für den Projectathon für healthinal als Sender eine OID in Gazelle definieren?
Dann könnte man gerade eine Sub-OID in der Basic Ressource setzen und auf den Server laden.

**Comment by joelfisch** [comment]
@ziegm 

Das klingt grundsätzlich sinnvoll, ich werde möglicherweise bei der konkreten Umsetzung nochmals nachfragen müssen. Was für mich hilfreich wäre, wenn du oder jemand anders auf unserem Testserver oder JSON ein eingehendes Bundle zur Verfügung stellen könnte. Im JSON müsste die OID noch ergänzt werden (sobald sie erstellt ist), auf die der ServiceRequest überprüft werden kann, ist das korrekt?
Ausgehende Bundles sind einfach alle, welche keinen entsprechenden Identifier haben?

**Comment by ziegm** [comment]
@joelfisch 

Achtung: Wir haben ein-und ausgehendes Bundle verdreht...

Korrekt wäre es so:

**Ausgehendes Bundle:** Im ServiceRequest ist der placerOrderIdentifier identisch zu dem placerOrderIdentifier in dieser [Basic Ressource](https://github.com/ahdis/matchbox-formfiller/blob/master/src/examples/placer-order-identifier.json) auf dem Server.

**Eingehendes Bundle:** Der placerOrderIdentifier im ServiceRequest entspricht nicht dem aus der Basic Ressource.

**Comment by joelfisch** [comment]
Vielen Dank für die Bundles, dieser Punkt aus dem soeben von mir gesendeten E-Mail erledigt sich damit 😉

**Comment by ziegm** [comment]
Die aktuelle OID ist die von ahdis mit .1.2.3 als Subdomain:
2.16.756.5.30.1.145.1.2.3
